name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: Dependencies
      run: bundle exec pod install
    - name: Build
      run: xcodebuild test -workspace "Laboratory.xcworkspace" -scheme "Laboratory" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest"
