name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: Bundle Install
      run: bundle install
    - name: Dependencies
      run: bundle exec pod install
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: List Simulators
      run: xcrun instruments -s
    - name: Build
      run: xcodebuild -workspace "Laboratory.xcworkspace" -scheme "Laboratory" -destination "platform=iOS Simulator,name=iPhone 8,OS=latest"
